
FROM openjdk:17.0.2-oraclelinux8

WORKDIR /app

COPY target/selenium-automationu-0.0.1-SNAPSHOT.jar selenium-automationu-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar", "selenium-automationu-0.0.1-SNAPSHOT.jar"]